# Generated by Django 3.2.8 on 2021-10-10 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cinemas', models.CharField(blank=True, max_length=50)),
                ('address_cinemas', models.CharField(blank=True, max_length=100)),
                ('image1_cinemas', models.TextField(blank=True)),
                ('image2_cinemas', models.TextField(blank=True)),
                ('image3_cinemas', models.TextField(blank=True)),
                ('info_cinemas', models.CharField(blank=True, max_length=100)),
                ('map_cinemas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_session', models.DateTimeField(blank=True)),
                ('hallnumber_session', models.IntegerField(blank=True)),
                ('countplaces_session', models.IntegerField(blank=True)),
                ('info_session', models.CharField(max_length=50)),
                ('price_session', models.IntegerField()),
                ('ID_cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cinemas')),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_film', models.CharField(blank=True, max_length=50)),
                ('image_film', models.TextField(blank=True)),
                ('video_film', models.TextField(blank=True)),
                ('info_film', models.TextField(blank=True)),
                ('genre_film', models.CharField(blank=True, max_length=50)),
                ('ID_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.session')),
            ],
        ),
    ]
