# Generated by Django 3.2.8 on 2021-10-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='short_info_film',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
