# Generated by Django 3.2.8 on 2021-10-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_films_video_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemas',
            name='image1_cinemas',
            field=models.ImageField(blank=True, upload_to='media/databaseImageCinemas'),
        ),
        migrations.AlterField(
            model_name='cinemas',
            name='image2_cinemas',
            field=models.ImageField(blank=True, upload_to='media/databaseImageCinemas'),
        ),
        migrations.AlterField(
            model_name='cinemas',
            name='image3_cinemas',
            field=models.ImageField(blank=True, upload_to='media/databaseImageCinemas'),
        ),
    ]
