# Generated by Django 3.2.8 on 2021-10-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211016_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemas',
            name='info_photo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cinemas',
            name='info_photo2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cinemas',
            name='info_photo3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cinemas',
            name='image1_cinemas',
            field=models.ImageField(blank=True, upload_to='media/databaseImageCinemas'),
        ),
        migrations.AlterField(
            model_name='cinemas',
            name='image2_cinemas',
            field=models.ImageField(blank=True, upload_to='media/databaseImageCinemas'),
        ),
        migrations.AlterField(
            model_name='cinemas',
            name='image3_cinemas',
            field=models.ImageField(blank=True, upload_to='media/databaseImageCinemas'),
        ),
    ]
