# Generated by Django 3.2.8 on 2021-11-14 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211017_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='ID_session',
        ),
        migrations.AddField(
            model_name='session',
            name='ID_Films',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.films'),
            preserve_default=False,
        ),
    ]
