# Generated by Django 3.2.8 on 2021-11-17 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_auto_20211114_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataSales', models.DateTimeField(blank=True)),
                ('countTicket', models.IntegerField()),
                ('price_session', models.IntegerField()),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sessions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.session')),
            ],
        ),
    ]
